spring.application.name=gestion_actifs

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_actifs?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

jwt.secret=gestion_actifs_secret_key_tres_longue_2026_application
jwt.expiration=86400000

server.error.include-message=always
server.error.include-stacktrace=always

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG